### ISSUE TITLE
你好，你的私仓里的jar包下载不下来了呀。

### ISSUE THREAD

**Issue by singledemon** [xuanbg/insight_message#3]
你好，你的私仓里的jar包下载不下来了呀。

**Comment by xuanbg** [comment]
你可以克隆下面这几个项目自己编译，再发布包到自己的maven私库。
https://github.com/xuanbg/insight.utils
https://github.com/xuanbg/insight.utils.redis

**Comment by xuanbg** [comment]
> 你好，你的私仓里的jar包下载不下来了呀。

你可以克隆下面这几个项目自己编译，再发布包到自己的maven私库。
https://github.com/xuanbg/insight.utils
https://github.com/xuanbg/insight.utils.redis

**Comment by singledemon** [comment]
> > 你好，你的私仓里的jar包下载不下来了呀。
> 
> 你可以克隆下面这几个项目自己编译，再发布包到自己的maven私库。
> https://github.com/xuanbg/insight.utils
> https://github.com/xuanbg/insight.utils.redis

好的。收到。感谢感谢。

**Comment by singledemon** [comment]
你好。你这个项目的配置文件里面都配置了那些参数可以帮忙看看吗，我这边启动的时候是报错的。

**Comment by xuanbg** [comment]
> 你好。你这个项目的配置文件里面都配置了那些参数可以帮忙看看吗，我这边启动的时候是报错的。

server:
  port: 6201
spring:
  datasource:
    url: jdbc:mysql://192.168.160.8/insight_message?useUnicode=true&characterEncoding=utf-8&useSSL=false
    hikari:
      connection-init-sql: set names utf8mb4
    username: root
    password: root
    tomcat:
      initial-size: 5
      min-idle: 5
      max-idle: 20
      max-wait: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.xxx.com
    port: 587
    username: xxx
    password: xxx
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: 192.168.160.8
    port: 6379
    password: root
    database: 1
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1
  rabbitmq:
    addresses: 192.168.160.8:5672
    username: root
    password: root
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 10
        prefetch: 1
    publisher-confirms: false
    publisher-returns: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.160.8:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
ribbon:
  ServerListRefreshInterval: 3000
  ReadTimeout: 10000
  ConnectTimeout: 5000
logging:
  level:
    com.insight: debug
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] %logger{35}: %msg%n'
mybatis:
  configuration:
    map-underscore-to-camel-case: true
insight:
  mail:
    sender: xxx

**Comment by xuanbg** [comment]
> 你好。你这个项目的配置文件里面都配置了那些参数可以帮忙看看吗，我这边启动的时候是报错的。

```
server:
  port: 6201
spring:
  datasource:
    url: jdbc:mysql://192.168.160.8/insight_message?useUnicode=true&characterEncoding=utf-8&useSSL=false
    hikari:
      connection-init-sql: set names utf8mb4
    username: root
    password: root
    tomcat:
      initial-size: 5
      min-idle: 5
      max-idle: 20
      max-wait: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.xxx.com
    port: 587
    username: xxx
    password: xxx
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: 192.168.160.8
    port: 6379
    password: root
    database: 1
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1
  rabbitmq:
    addresses: 192.168.160.8:5672
    username: root
    password: root
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 10
        prefetch: 1
    publisher-confirms: false
    publisher-returns: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.160.8:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
ribbon:
  ServerListRefreshInterval: 3000
  ReadTimeout: 10000
  ConnectTimeout: 5000
logging:
  level:
    com.insight: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
insight:
  mail:
    sender: xxx
```
